# GitHub Pages Configuration for Al-Hemam Center Project
title: "مشروع مركز الهمم - العرض الرقمي الشامل"
description: "عرض سعر وتقني شامل لتطوير الحلول الرقمية لمركز الهمم في جدة"
author: "خالد جمال عبدالناصر"
email: "khaledjamal51@gmail.com"

# Site settings
lang: ar
timezone: Asia/Riyadh
baseurl: ""

# GitHub Pages settings
plugins:
  - jekyll-sitemap
  - jekyll-feed

# Exclude files from processing
exclude:
  - node_modules/
  - src/
  - .env*
  - package*.json
  - README.md

# Include files
include:
  - _config.yml
  - index.html

# Markdown settings
markdown: kramdown
highlighter: rouge

# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"
      lang: "ar"
      dir: "rtl"
