#!/bin/bash

echo "🚀 إعداد SSH بدون كلمة مرور - الطريقة اليدوية"
echo ""
echo "📋 الخطوات:"
echo "1. انسخ المفتاح العام التالي:"
echo ""
cat ~/.ssh/id_rsa.pub
echo ""
echo "2. اتصل بالخادم:"
echo "   ssh ubuntu@100.64.64.33"
echo "   (استخدم كلمة المرور: root)"
echo ""
echo "3. على الخادم، نفذ الأوامر التالية:"
echo "   mkdir -p ~/.ssh"
echo "   chmod 700 ~/.ssh"
echo "   echo '$(cat ~/.ssh/id_rsa.pub)' >> ~/.ssh/authorized_keys"
echo "   chmod 600 ~/.ssh/authorized_keys"
echo ""
echo "4. لإعداد Tailscale ليعمل في الخلفية:"
echo "   sudo tailscale down"
echo "   sudo tailscale up --accept-routes --accept-dns=false"
echo "   sudo systemctl enable tailscaled"
echo "   sudo systemctl start tailscaled"
echo "   tailscale status"
echo ""
echo "5. اختبر الاتصال بدون كلمة مرور:"
echo "   ssh ubuntu@100.64.64.33"
echo ""
echo "✅ بعد تنفيذ هذه الخطوات، ستحصل على:"
echo "   - SSH بدون كلمة مرور"
echo "   - Tailscale يعمل في الخلفية دائماً"
