-- ================================================================
-- 🚀 PROPOSED PERFORMANCE IMPROVEMENTS MIGRATION
-- ================================================================
-- Generated by: DBA Integrity Agent
-- Date: 2025-11-01
-- Purpose: Add missing indexes and constraints based on integrity analysis
-- Status: PROPOSED (NOT YET APPLIED)
-- ================================================================
--
-- INSTRUCTIONS:
-- 1. Review this migration file carefully
-- 2. Test in development environment first
-- 3. Run EXPLAIN ANALYZE on affected queries before and after
-- 4. Apply to production during low-traffic window
-- 5. Monitor query performance after deployment
--
-- ================================================================

-- ============================================================
-- PART 1: ADD MISSING COMPOSITE INDEXES
-- ============================================================

-- Insurance Claims: Patient + Status queries
CREATE INDEX IF NOT EXISTS idx_insurance_claims_patient_status 
  ON insurance_claims(patient_id, status);

COMMENT ON INDEX idx_insurance_claims_patient_status IS 
  'Composite index for patient-specific claims filtering. 
   Estimated improvement: 30-50% on claims queries.';

-- Sessions: Date + Status queries (for scheduling)
CREATE INDEX IF NOT EXISTS idx_sessions_date_status 
  ON sessions(session_date, status);

COMMENT ON INDEX idx_sessions_date_status IS 
  'Composite index for session scheduling and availability checks.
   Estimated improvement: 20-40% on session queries.';

-- ============================================================
-- PART 2: ADD MISSING SINGLE-COLUMN INDEXES
-- ============================================================

-- Translations: Namespace filtering
CREATE INDEX IF NOT EXISTS idx_translations_namespace 
  ON translations(namespace);

COMMENT ON INDEX idx_translations_namespace IS 
  'Single-column index for namespace-based translation queries.
   Estimated improvement: 10-20% on translation queries.';

-- Insurance Claims: Submission date (for reporting)
CREATE INDEX IF NOT EXISTS idx_insurance_claims_submitted_date 
  ON insurance_claims(submitted_date) 
  WHERE submitted_date IS NOT NULL;

COMMENT ON INDEX idx_insurance_claims_submitted_date IS 
  'Partial index for date-range queries on submitted claims.
   Used in reporting and analytics.';

-- ============================================================
-- PART 3: ADD UNIQUE CONSTRAINTS FOR DATA INTEGRITY
-- ============================================================

-- Patients: Email uniqueness (when not null)
-- This prevents duplicate patient records with same email
DO $$ 
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_indexes 
    WHERE indexname = 'idx_patients_email_unique'
  ) THEN
    CREATE UNIQUE INDEX idx_patients_email_unique 
      ON patients(email) 
      WHERE email IS NOT NULL AND email != '';
    
    RAISE NOTICE 'Created unique index on patients.email';
  ELSE
    RAISE NOTICE 'Unique index on patients.email already exists';
  END IF;
END $$;

COMMENT ON INDEX idx_patients_email_unique IS 
  'Unique constraint on patient email addresses (when not null).
   Prevents duplicate patient records.';

-- Doctors: Email uniqueness (when not null)
DO $$ 
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_indexes 
    WHERE indexname = 'idx_doctors_email_unique'
  ) THEN
    CREATE UNIQUE INDEX idx_doctors_email_unique 
      ON doctors(email) 
      WHERE email IS NOT NULL AND email != '';
    
    RAISE NOTICE 'Created unique index on doctors.email';
  ELSE
    RAISE NOTICE 'Unique index on doctors.email already exists';
  END IF;
END $$;

COMMENT ON INDEX idx_doctors_email_unique IS 
  'Unique constraint on doctor email addresses (when not null).
   Prevents duplicate doctor records.';

-- ============================================================
-- PART 4: OPTIMIZE EXISTING INDEXES
-- ============================================================

-- Add partial index for active appointments (most common query)
CREATE INDEX IF NOT EXISTS idx_appointments_active 
  ON appointments(scheduled_at, doctor_id, patient_id)
  WHERE status IN ('pending', 'confirmed');

COMMENT ON INDEX idx_appointments_active IS 
  'Composite partial index for active appointments.
   Covers most common appointment lookup queries.';

-- Add partial index for pending payments
CREATE INDEX IF NOT EXISTS idx_payments_pending 
  ON payments(appointment_id, amount)
  WHERE status = 'pending';

COMMENT ON INDEX idx_payments_pending IS 
  'Partial index for pending payment lookups.
   Used in billing and reminder systems.';

-- ============================================================
-- PART 5: CREATE MATERIALIZED VIEW FOR DASHBOARD STATS
-- ============================================================
-- This addresses the N+1 query problem in dashboard statistics

CREATE MATERIALIZED VIEW IF NOT EXISTS dashboard_statistics AS
SELECT
  -- Patients
  (SELECT COUNT(*) FROM patients) AS total_patients,
  (SELECT COUNT(*) FROM patients WHERE activated = true) AS active_patients,
  (SELECT COUNT(*) FROM patients WHERE status = 'blocked') AS blocked_patients,
  
  -- Appointments
  (SELECT COUNT(*) FROM appointments) AS total_appointments,
  (SELECT COUNT(*) FROM appointments WHERE status = 'completed') AS completed_appointments,
  (SELECT COUNT(*) FROM appointments WHERE status = 'pending') AS pending_appointments,
  
  -- Payments
  (SELECT COALESCE(SUM(amount), 0) FROM payments WHERE status = 'paid') AS total_revenue,
  (SELECT COALESCE(SUM(amount), 0) FROM payments 
   WHERE status = 'paid' AND created_at >= NOW() - INTERVAL '30 days') AS monthly_revenue,
  
  -- Insurance Claims
  (SELECT COUNT(*) FROM insurance_claims) AS total_claims,
  (SELECT COUNT(*) FROM insurance_claims WHERE status = 'approved') AS approved_claims,
  (SELECT COUNT(*) FROM insurance_claims WHERE status = 'pending') AS pending_claims,
  (SELECT COUNT(*) FROM insurance_claims WHERE status = 'rejected') AS rejected_claims,
  
  -- Staff
  (SELECT COUNT(*) FROM users WHERE role IN ('doctor', 'nurse', 'staff', 'therapist')) AS total_staff,
  (SELECT COUNT(*) FROM users WHERE role IN ('doctor', 'nurse', 'staff', 'therapist') AND status = 'active') AS active_staff,
  
  -- Sessions
  (SELECT COUNT(*) FROM sessions) AS total_sessions,
  (SELECT COUNT(*) FROM sessions WHERE status = 'completed') AS completed_sessions,
  (SELECT COUNT(*) FROM sessions WHERE status IN ('scheduled', 'confirmed')) AS upcoming_sessions,
  
  -- Timestamp
  NOW() AS last_updated;

-- Create index on the materialized view
CREATE UNIQUE INDEX IF NOT EXISTS idx_dashboard_statistics_updated 
  ON dashboard_statistics(last_updated);

COMMENT ON MATERIALIZED VIEW dashboard_statistics IS 
  'Materialized view for dashboard statistics.
   Addresses N+1 query problem in dashboard endpoint.
   Refresh every 5-10 minutes or use trigger-based refresh.
   Estimated improvement: 90% reduction in query time.';

-- ============================================================
-- PART 6: CREATE REFRESH FUNCTION FOR MATERIALIZED VIEW
-- ============================================================

-- Function to refresh dashboard statistics
CREATE OR REPLACE FUNCTION refresh_dashboard_statistics()
RETURNS void AS $$
BEGIN
  REFRESH MATERIALIZED VIEW CONCURRENTLY dashboard_statistics;
  
  -- Log the refresh
  INSERT INTO audit_logs (
    action,
    resource_type,
    metadata,
    created_at
  ) VALUES (
    'materialized_view_refreshed',
    'dashboard_statistics',
    jsonb_build_object(
      'refreshed_at', NOW(),
      'method', 'scheduled'
    ),
    NOW()
  );
  
EXCEPTION WHEN OTHERS THEN
  -- Log error but don't fail
  INSERT INTO audit_logs (
    action,
    resource_type,
    metadata,
    severity,
    error_message,
    created_at
  ) VALUES (
    'materialized_view_refresh_failed',
    'dashboard_statistics',
    jsonb_build_object(
      'attempted_at', NOW(),
      'error', SQLERRM
    ),
    'error',
    SQLERRM,
    NOW()
  );
END;
$$ LANGUAGE plpgsql;

COMMENT ON FUNCTION refresh_dashboard_statistics IS 
  'Refreshes the dashboard_statistics materialized view.
   Should be called every 5-10 minutes via cron job or pg_cron.';

-- ============================================================
-- PART 7: CREATE TRIGGER FOR AUTOMATIC REFRESH (OPTIONAL)
-- ============================================================

-- NOTE: This is an aggressive approach. For production, consider
-- using a scheduled refresh instead (every 5-10 minutes)

-- Create function to invalidate dashboard stats
CREATE OR REPLACE FUNCTION invalidate_dashboard_statistics()
RETURNS TRIGGER AS $$
BEGIN
  -- Mark for refresh (using a flag table or just refresh immediately)
  -- For now, we'll just log it
  -- PERFORM refresh_dashboard_statistics(); -- Don't do this on every insert!
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Optional triggers (commented out - use scheduled refresh instead)
-- CREATE TRIGGER trigger_refresh_dashboard_on_patient_change
--   AFTER INSERT OR UPDATE OR DELETE ON patients
--   FOR EACH STATEMENT
--   EXECUTE FUNCTION invalidate_dashboard_statistics();

-- ============================================================
-- PART 8: ANALYZE TABLES FOR QUERY PLANNER
-- ============================================================

-- Update statistics for query planner optimization
ANALYZE patients;
ANALYZE doctors;
ANALYZE appointments;
ANALYZE sessions;
ANALYZE payments;
ANALYZE insurance_claims;
ANALYZE translations;
ANALYZE users;

-- ============================================================
-- PART 9: VERIFICATION QUERIES
-- ============================================================

-- Verify indexes were created
DO $$
DECLARE
  idx_count INTEGER;
BEGIN
  SELECT COUNT(*) INTO idx_count
  FROM pg_indexes
  WHERE indexname LIKE 'idx_%_patient_status'
     OR indexname LIKE 'idx_%_date_status'
     OR indexname LIKE 'idx_%_namespace'
     OR indexname LIKE 'idx_%_email_unique'
     OR indexname LIKE 'idx_%_active'
     OR indexname LIKE 'idx_%_pending';
  
  RAISE NOTICE 'Created % new indexes', idx_count;
END $$;

-- Verify materialized view exists
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_matviews 
    WHERE matviewname = 'dashboard_statistics'
  ) THEN
    RAISE NOTICE 'Materialized view dashboard_statistics created successfully';
  ELSE
    RAISE WARNING 'Failed to create materialized view dashboard_statistics';
  END IF;
END $$;

-- ============================================================
-- PART 10: PERFORMANCE TESTING QUERIES
-- ============================================================

-- Test queries to run before and after applying this migration
-- Compare execution times using EXPLAIN ANALYZE

-- Query 1: Patient claims by status
-- EXPLAIN ANALYZE
-- SELECT p.*, ic.status, COUNT(*) as claim_count
-- FROM patients p
-- JOIN insurance_claims ic ON ic.patient_id = p.id
-- WHERE ic.status = 'pending'
-- GROUP BY p.id, ic.status;

-- Query 2: Session scheduling
-- EXPLAIN ANALYZE
-- SELECT s.*, d.first_name, d.last_name
-- FROM sessions s
-- JOIN doctors d ON d.id = s.doctor_id
-- WHERE s.session_date = CURRENT_DATE
--   AND s.status IN ('scheduled', 'confirmed')
-- ORDER BY s.session_date, s.session_time;

-- Query 3: Translations by namespace
-- EXPLAIN ANALYZE
-- SELECT * FROM translations
-- WHERE namespace = 'common' AND locale = 'ar';

-- ============================================================
-- PART 11: ROLLBACK INSTRUCTIONS
-- ============================================================

-- To rollback this migration, execute:
--
-- DROP INDEX IF EXISTS idx_insurance_claims_patient_status;
-- DROP INDEX IF EXISTS idx_sessions_date_status;
-- DROP INDEX IF EXISTS idx_translations_namespace;
-- DROP INDEX IF EXISTS idx_insurance_claims_submitted_date;
-- DROP INDEX IF EXISTS idx_patients_email_unique;
-- DROP INDEX IF EXISTS idx_doctors_email_unique;
-- DROP INDEX IF EXISTS idx_appointments_active;
-- DROP INDEX IF EXISTS idx_payments_pending;
-- DROP MATERIALIZED VIEW IF EXISTS dashboard_statistics;
-- DROP FUNCTION IF EXISTS refresh_dashboard_statistics();
-- DROP FUNCTION IF EXISTS invalidate_dashboard_statistics();

-- ============================================================
-- MIGRATION LOG
-- ============================================================

DO $$
BEGIN
  IF EXISTS (SELECT FROM information_schema.tables WHERE table_name = 'audit_logs') THEN
    INSERT INTO audit_logs (
      action,
      resource_type,
      metadata,
      created_at
    ) VALUES (
      'migration_applied',
      'performance_improvements',
      jsonb_build_object(
        'migration', '053_proposed_performance_improvements',
        'date', NOW(),
        'description', 'Performance optimization migration with composite indexes and materialized view',
        'changes', jsonb_build_array(
          'Added composite indexes for insurance_claims and sessions',
          'Added unique constraints on patient and doctor emails',
          'Created materialized view for dashboard statistics',
          'Added partial indexes for active records',
          'Optimized query planner statistics'
        ),
        'estimated_improvements', jsonb_build_object(
          'insurance_claims_queries', '30-50% faster',
          'session_queries', '20-40% faster',
          'dashboard_endpoint', '90% faster (from ~500ms to ~50ms)',
          'translation_queries', '10-20% faster'
        )
      ),
      NOW()
    );
  END IF;
END $$;

-- ============================================================
-- NOTES FOR DEPLOYMENT
-- ============================================================

-- 1. BEFORE APPLYING:
--    - Backup database
--    - Run EXPLAIN ANALYZE on affected queries
--    - Note current query execution times
--    - Schedule during low-traffic window

-- 2. AFTER APPLYING:
--    - Verify all indexes created (check pg_indexes)
--    - Test materialized view refresh
--    - Run EXPLAIN ANALYZE again and compare
--    - Monitor slow query logs
--    - Set up cron job for materialized view refresh

-- 3. MONITORING:
--    - Track query execution times
--    - Monitor index usage (pg_stat_user_indexes)
--    - Check materialized view freshness
--    - Alert if refresh fails

-- 4. SCHEDULED REFRESH (Recommended):
--    - Use pg_cron or external scheduler
--    - Refresh every 5-10 minutes during business hours
--    - Refresh every 30-60 minutes during off-hours
--    - Example pg_cron: 
--      SELECT cron.schedule('refresh-dashboard', '*/5 * * * *', 
--        'SELECT refresh_dashboard_statistics()');

-- ============================================================
-- END OF MIGRATION
-- ============================================================
