name: CI — Security / Tests / Auto-Fix

on:
  push:
    branches: [main, develop, 'cursor/**']
  pull_request:
    branches: [main, develop]
  schedule:
    # Run daily at 2 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:

env:
  NODE_VERSION: '20'
  PLAYWRIGHT_BROWSERS_PATH: 0

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Cache node modules
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Cache Playwright browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-playwright-

  lint-and-fix:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run ESLint (auto-fix)
        run: |
          npx eslint "src/**/*.{ts,tsx,js,jsx}" --fix --max-warnings 0 || echo "ESLint issues found (some may be auto-fixed)"

      - name: Replace console.* with logger (safe)
        run: |
          if [ -f "scripts/replace-console.js" ]; then
            node ./scripts/replace-console.js
          else
            echo "replace-console.js not found, skipping"
          fi

      - name: Check for uncommitted changes
        id: check-changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            echo "has_changes=true" >> $GITHUB_OUTPUT
          else
            echo "has_changes=false" >> $GITHUB_OUTPUT
          fi

      - name: Commit fixes
        if: steps.check-changes.outputs.has_changes == 'true'
        run: |
          git config user.name "Moeen CI Agent"
          git config user.email "ci-agent@moeen.app"
          git add -A
          git commit -m "chore: auto-fixes from CI (lint, console.log replacement)" || echo "commit failed"
          git push || echo "push failed (no permission or no changes)"

  security-scan:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check for unprotected API routes
        run: |
          echo "Scanning for unprotected routes..."
          grep -r "export async function" src/app/api --include="*.ts" | \
            grep -v "requireAuth\|authorize" | \
            head -20 || echo "All routes appear protected"

      - name: Check for direct process.env usage
        run: |
          echo "Checking for direct process.env usage..."
          grep -r "process\.env\." src/app/api --include="*.ts" | \
            grep -v "NODE_ENV\|PLAYWRIGHT" | \
            head -10 || echo "No direct process.env usage found (good!)"

      - name: Check for console.log statements
        run: |
          echo "Checking for console.log statements..."
          grep -r "console\.\(log\|error\|warn\|info\|debug\)" src --include="*.ts" --include="*.tsx" | \
            head -20 || echo "No console statements found (good!)"

  type-check:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Type check
        run: npm run type:check || echo "Type errors found (non-blocking in CI)"

  test:
    runs-on: ubuntu-latest
    needs: [install, lint-and-fix]
    timeout-minutes: 30
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright browsers
        run: npx playwright install --with-deps chromium

      - name: Setup environment variables
        run: |
          echo "Setting up test environment..."
          cp .env.example .env.test || echo ".env.example not found"
          echo "NODE_ENV=test" >> .env.test
          echo "NEXT_PUBLIC_SUPABASE_URL=${{ secrets.NEXT_PUBLIC_SUPABASE_URL || 'https://placeholder.supabase.co' }}" >> .env.test
          echo "SUPABASE_SERVICE_ROLE_KEY=${{ secrets.SUPABASE_SERVICE_ROLE_KEY || 'placeholder-key' }}" >> .env.test

      - name: Start dev server
        run: |
          npm run dev &
          echo $! > /tmp/dev-server.pid
          sleep 10
          npx wait-on http://localhost:3001 --timeout 60000 || echo "Server startup check"

      - name: Wait for server to be ready
        run: |
          for i in {1..30}; do
            if curl -f http://localhost:3001/api/health > /dev/null 2>&1; then
              echo "Server is ready"
              exit 0
            fi
            echo "Waiting for server... ($i/30)"
            sleep 2
          done
          echo "Server may not be fully ready, continuing with tests"

      - name: Run Playwright tests
        run: |
          npx playwright test \
            --project=chromium \
            --reporter=list,html \
            --retries=1 \
            --workers=1 \
            || echo "Some tests failed"

      - name: Stop dev server
        if: always()
        run: |
          if [ -f /tmp/dev-server.pid ]; then
            kill $(cat /tmp/dev-server.pid) || true
          fi
          pkill -f "next dev" || true

  test-api-security:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run API security tests
        run: |
          npm run dev &
          sleep 15
          npx playwright test tests/api/production-security-routes.spec.ts \
            --project=chromium \
            --reporter=list \
            || echo "Security tests completed with some failures"

      - name: Stop dev server
        if: always()
        run: pkill -f "next dev" || true

  report:
    runs-on: ubuntu-latest
    needs: [test, test-api-security, security-scan, type-check]
    if: always()
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create test summary
        run: |
          mkdir -p .cursor-agent-reports
          cat > .cursor-agent-reports/test-summary.json << EOF
          {
            "timestamp": "$(date -u +%Y-%m-%dT%H:%M:%SZ)",
            "workflow": "${{ github.workflow }}",
            "run_id": "${{ github.run_id }}",
            "commit": "${{ github.sha }}",
            "branch": "${{ github.ref_name }}",
            "jobs": {
              "test": "${{ needs.test.result }}",
              "test-api-security": "${{ needs.test-api-security.result }}",
              "security-scan": "${{ needs.security-scan.result }}",
              "type-check": "${{ needs.type-check.result }}"
            }
          }
          EOF

      - name: Upload Playwright report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report-${{ github.run_id }}
          path: |
            playwright-report/
            .cursor-agent-reports/
          retention-days: 30

      - name: Upload test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-${{ github.run_id }}
          path: test-results/
          retention-days: 7
