name: CI

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ chore/merge-orbit-home ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Lint and typecheck
        run: |
          npm run lint:check
          npm run type:check

      - name: Install Playwright browsers
        run: npx playwright install --with-deps

      - name: Build
        run: npm run build

      - name: Start server
        run: npm run dev &

      - name: Wait for server
        uses: jakejarvis/wait-action@v0.1.1
        with:
          url: 'http://localhost:3001'
          timeout: '120000'

      - name: Run Playwright tests
        env:
          PLAYWRIGHT_BASE_URL: http://localhost:3001
        run: npm run test

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: playwright-report
